# Generated by Django 3.2.2 on 2021-07-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=264)),
                ('ten_dang_nhap', models.CharField(max_length=50)),
                ('mat_khau', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dia_chi', models.TextField()),
            ],
            options={
                'db_table': 'KhachHang',
            },
        ),
    ]
